#!/bin/bash


echo "Start $0 ver.3 - PART 1"
echo "Script LFS - by Dertin!!

"

read -p "Enter partition to format [ext3] {eg: sda1}: " P1
mke2fs -jv /dev/$P1
echo "Format... /dev/$P1  [  OK  ]"
read -p "Enter partition swap {eg: sda2} " P2
mkswap /dev/$P2
echo "Mkswap... /dev/$P2  [  OK  ]
"


echo "Mount $P1 & Swapon $P2"
export DER=/mnt/dertin
mkdir -pv $DER
mount -v -t ext3 /dev/$P1 $DER
/sbin/swapon -v /dev/$P2
echo "Mount & Swapon   [  OK  ]
"

echo "Go to the directory: $DER"
cd $DER
echo "Create the directory: sources"
mkdir -v sources
chmod -v a+wt sources
echo "Create the directory: tools"
mkdir -v tools
echo "link $DER/tools - /"
ln -sv $DER/tools /
echo "Adding the dertin User"
groupadd user
useradd -s /bin/bash -g user -m -k /dev/null dertin
passwd dertin

chown -v dertin $DER/tools
chown -v dertin $DER/sources

cd /home/dertin
wget http://dertin.googlecode.com/files/dertin-linux-PART2
chmod 777 dertin-linux-PART2

echo "MANUALLY run the script ./dertin-linux-PART2
MANUALLY run the script ./dertin-linux-PART2
MANUALLY run the script ./dertin-linux-PART2"

su - dertin






