#!/bin/bash

echo "Start ver.3.1 - PART 2"
echo "Script UP!!
..........................................................
"
echo "~/.bash_profile & ~/.bashrc      [  OK  ]
"
cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
DER=/mnt/dertin
LC_ALL=POSIX
DER_TGT=$(uname -m)-dertin-linux-gnu
PATH=/tools/bin:/bin:/usr/bin
export DER LC_ALL DER_TGT PATH
EOF

cd /home/dertin
wget http://dertin.googlecode.com/files/dertin-linux-PART3
chmod 777 dertin-linux-PART3

echo "MANUALLY run the script ./dertin-linux-PART3
MANUALLY run the script ./dertin-linux-PART3
MANUALLY run the script ./dertin-linux-PART3"

source ~/.bash_profile
